services: 
  database: 
    image: postgres:latest
    container_name: postgres
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports: 
      - "${POSTGRES_PORT}:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    restart: 
      always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "${ELASTIC_PORT}:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    mem_limit: 1g

  logstash:
    image: docker.elastic.co/logstash/logstash:9.2.3
    container_name: logstash
    environment:
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - BATCH_SIZE=${BATCH_SIZE}
      - BATCH_DELAY=${BATCH_DELAY}
      - LOGSTASH_TCP_PORT=${LOGSTASH_TCP_PORT}
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "${LOGSTASH_TCP_PORT}:5000"
    depends_on:
      - elasticsearch

volumes: 
  postgres_data: 
  elasticsearch_data: